default_platform(:android)

platform :android do
  desc "Build Android release APK"
  lane :qa do
    gradle(
      project_dir: "android",
      task: "assemble",
      build_type: "Release"
    )
  end
end