default_platform(:android)

platform :android do
  desc "Build Android release APK and upload to Appcircle Testing Distribution"
  lane :qa do
    gradle(
      project_dir: "android",
      task: "assemble",
      build_type: "Release"
    )

    apk_path = "./android/app/build/outputs/apk/release/app-release.apk"

    appcircle_testing_distribution(
      personalAPIToken: ENV["AC_PERSONAL_API_TOKEN"],
      profileName: ENV["APPCIRCLE_PROFILE_NAME"],
      createProfileIfNotExists: true,
      appPath: apk_path,
      message: "QA build #{ENV['GITHUB_REF']} @ #{ENV['GITHUB_SHA'][0..6]}"
    )
  end
end